export const SLASH_COMMANDS = {
	settings: { hint: "Open settings menu" },
	model: { hint: "Switch to a specific model" },
	"scoped-models": { hint: "Enable or disable models for Ctrl+P cycling" },
	"multi-model": { hint: "Configure model roles" },
	ferment: { hint: "Run task in background" },
	todos: { hint: "Open todo overlay / manage short-lived todo items" },
	compact: { hint: "Compact context window" },
	name: { hint: "Rename this session" },
	new: { hint: "Start a new session" },
	agents: { hint: "Manage background agents" },
	permissions: { hint: "View or change permission mode and rules" },
	phase: { hint: "Show or change the current work phase" },
	bug: { hint: "Report a bug — opens GitHub issue form" },
	stats: { hint: "View coding analytics and metrics" },
	mcp: { hint: "Show MCP server status" },
	resources: { hint: "Manage resources (files, URLs, images)" },
	tags: { hint: "Manage usage tracking tags" },
	tips: { hint: "Show all tips" },
	help: { hint: "Show this help" },
	exit: { hint: "Exit the application" },
}
